### ISSUE TITLE
Incorrect Queenbeet parents

### ISSUE THREAD

**Issue by moussetc** [Hamusutaa/cookie-garden-progress#1]
Hi and thank you for making&sharing this mod, it's nice to have!
Just so you know, the mod indicates that Queenbeet are children of Chocoroot and White Mildew, but the wiki says it's Chocoroot and **Bakeberry**, and I looked briefly at the code, which seems to concurr.
Have a nice day :cookie:

**Comment by Hamusutaa** [comment]
You are correct.  I will issue a fix in the next release (some time today).
